# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBLogReportDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_datetime', models.DateTimeField(help_text=b'Datetime representation of the hour for which logs '
                                                                b'are stored in the log file')),
                ('log_file_path', models.CharField(help_text=b'Relative path of the stored log file in S3 bucket',
                                                   max_length=1024)),
                ('log_report_path', models.CharField(blank=True, help_text=b'Relative path of the stored report in '
                                                                           b'S3 bucket', max_length=1024, null=True)),
            ],
        ),
    ]
