# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_analyser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dblogreportdetail',
            name='db_instance',
            field=models.CharField(blank=True, help_text=b'Name of the DB Instance to which the logs belong',
                                   max_length=64, null=True),
        ),
    ]
